### ISSUE TITLE
Repeating Error within Logs-- preventing startup... (Error at ClamAV update.)

### ISSUE THREAD

**Issue by Aceriz** [mko-x/docker-clamav#103] opened 2021-03-11 17:51 UTC
Hey I am running on Unraid 6.9.1.  Running your docker-clamav: alpine.  I keep getting the below error over and over every 5 seconds. 

I have tried deleting the docker and tried deleting the docker and appdata folders without success.. 

below is screenshot of my config docker setup 
" in extra parameters =   -p 3310:3310 --hostname=clamavsrv --restart=unless-stopped  "

![image](https://user-images.githubusercontent.com/23278427/110831659-7240ef80-8268-11eb-8327-6704c8725bfc.png)

[bootstrap] Initial clam DB download.
Thu Mar 11 17:44:55 2021 -> ClamAV update process started at Thu Mar 11 17:44:55 2021
Thu Mar 11 17:44:55 2021 -> daily database available for download (remote version: 26105)

Thu Mar 11 17:44:55 2021 -> ^downloadFile: Unexpected response (429) from https://database.clamav.net/daily.cvd
Thu Mar 11 17:44:55 2021 -> ^getcvd: Can't download daily.cvd from https://database.clamav.net/daily.cvd
Thu Mar 11 17:44:55 2021 -> Trying again in 5 secs...
Thu Mar 11 17:45:00 2021 -> daily database available for download (remote version: 26105)

Thu Mar 11 17:45:00 2021 -> daily database available for download (remote version: 26105)

Thu Mar 11 17:45:00 2021 -> ^downloadFile: Unexpected response (429) from https://database.clamav.net/daily.cvd
Thu Mar 11 17:45:00 2021 -> ^getcvd: Can't download daily.cvd from https://database.clamav.net/daily.cvd
Thu Mar 11 17:45:00 2021 -> Trying again in 5 secs...
Thu Mar 11 17:45:05 2021 -> daily database available for download (remote version: 26105)

Thu Mar 11 17:45:05 2021 -> !downloadFile: Unexpected response (429) from https://database.clamav.net/daily.cvd
Thu Mar 11 17:45:05 2021 -> !getcvd: Can't download daily.cvd from https://database.clamav.net/daily.cvd
Thu Mar 11 17:45:05 2021 -> Giving up on https://database.clamav.net...
Thu Mar 11 17:45:05 2021 -> !Update failed for database: daily

Thu Mar 11 17:45:05 2021 -> ^fc_update_databases: fc_update_database failed: HTTP GET failed (11)

Thu Mar 11 17:45:05 2021 -> !Database update process failed: HTTP GET failed (11)

Thu Mar 11 17:45:05 2021 -> !Update failed.

**Comment by captrespect** [comment] 2021-03-12 14:27
429 is a too many requests error.  I'm not sure if that is just for you or everyone.  

I'm getting something similar trying to get the daily update:
        | Fri Mar 12 14:26:28 2021 -> ^downloadFile: file not found: https://database.clamav.net/daily-25971.cdiff
clam-av_1            | Fri Mar 12 14:26:28 2021 -> ^getpatch: Can't download daily-25971.cdiff from https://database.clamav.net/daily-25971.cdiff
clam-av_1            | Fri Mar 12 14:26:28 2021 -> ^downloadFile: file not found: https://database.clamav.net/daily-25971.cdiff
clam-av_1            | Fri Mar 12 14:26:28 2021 -> ^getpatch: Can't download daily-25971.cdiff from https://database.clamav.net/daily-25971.cdiff
clam-av_1            | Fri Mar 12 14:26:28 2021 -> ^downloadFile: file not found: https://database.clamav.net/daily-25971.cdiff
clam-av_1            | Fri Mar 12 14:26:28 2021 -> ^getpatch: Can't download daily-25971.cdiff from https://database.clamav.net/daily-25971.cdiff
clam-av_1            | Fri Mar 12 14:26:29 2021 -> ^downloadFile: file not found: https://database.clamav.net/daily-25971.cdiff
clam-av_1            | Fri Mar 12 14:26:29 2021 -> ^getpatch: Can't download daily-25971.cdiff from https://database.clamav.net/daily-25971.cdiff
clam-av_1            | Fri Mar 12 14:26:29 2021 -> ^downloadFile: file not found: https://database.clamav.net/daily-25971.cdiff
clam-av_1            | Fri Mar 12 14:26:29 2021 -> ^getpatch: Can't download daily-25971.cdiff from https://database.clamav.net/daily-25971.cdiff
clam-av_1            | Fri Mar 12 14:26:29 2021 -> ^Incremental update failed, trying to download daily.cvd

**Comment by mko-x** [comment] 2021-03-15 22:40
The download errors are not related to this docker image. It works fine in several tested configurations with different machines even in production in thousands of systems.

Does the error still occur?

**Comment by robkorv** [comment] 2021-03-18 09:57
I get the same error with the alphine, while buster-slim does work. In alphine the service is not available because of this. This is the log from alphine:

```
Thu Mar 18 09:34:51 2021 -> ClamAV update process started at Thu Mar 18 09:34:51 2021
Thu Mar 18 09:34:51 2021 -> daily database available for download (remote version: 26111)
Thu Mar 18 09:35:05 2021 -> Testing database: '/var/lib/clamav/tmp.0e738/clamav-722c9bf62d3e9d7723431d5e99feb494.tmp-daily.cvd' ...
Thu Mar 18 09:35:17 2021 -> Database test passed.
Thu Mar 18 09:35:17 2021 -> daily.cvd updated (version: 26111, sigs: 3961058, f-level: 63, builder: raynman)
Thu Mar 18 09:35:17 2021 -> main database available for download (remote version: 59)
Thu Mar 18 09:35:33 2021 -> Testing database: '/var/lib/clamav/tmp.0e738/clamav-15a75958b9b84de8ed8fc00241c5c371.tmp-main.cvd' ...
Thu Mar 18 09:35:38 2021 -> Database test passed.
Thu Mar 18 09:35:38 2021 -> main.cvd updated (version: 59, sigs: 4564902, f-level: 60, builder: sigmgr)
Thu Mar 18 09:35:38 2021 -> bytecode database available for download (remote version: 333)
Thu Mar 18 09:35:38 2021 -> Testing database: '/var/lib/clamav/tmp.0e738/clamav-8a6af0f28418e510b68967c3c8ca8ec7.tmp-bytecode.cvd' ...
Thu Mar 18 09:35:38 2021 -> Database test passed.
Thu Mar 18 09:35:38 2021 -> bytecode.cvd updated (version: 333, sigs: 92, f-level: 63, builder: awillia2)
Thu Mar 18 09:35:38 2021 -> safebrowsing database available for download (remote version: 49191)
Thu Mar 18 09:35:38 2021 -> ^downloadFile: Unexpected response (403) from https://database.clamav.net/safebrowsing.cvd
Thu Mar 18 09:35:38 2021 -> ^getcvd: Can't download safebrowsing.cvd from https://database.clamav.net/safebrowsing.cvd
Thu Mar 18 09:35:38 2021 -> Trying again in 5 secs...
Thu Mar 18 09:35:43 2021 -> safebrowsing database available for download (remote version: 49191)
Thu Mar 18 09:35:44 2021 -> ^downloadFile: Unexpected response (403) from https://database.clamav.net/safebrowsing.cvd
Thu Mar 18 09:35:44 2021 -> ^getcvd: Can't download safebrowsing.cvd from https://database.clamav.net/safebrowsing.cvd
Thu Mar 18 09:35:44 2021 -> Trying again in 5 secs...
```

When I open https://database.clamav.net/safebrowsing.cvd there is DDoS protection by Cloudflare. Maybe that's the problem here?

So for now a workable solution is to use buster-slim instead of alphine.

**Comment by qrjo** [comment] 2021-03-18 18:38
We're seeing the same 429 errors when trying to start the alpine version on two separate environments. Using buster-slim seems to fix the issue, but I'd like to go back to alpine.

**Comment by mko-x** [comment] 2021-03-18 20:14
Seems like different configurations for the safe browsing feature.

https://github.com/Cisco-Talos/clamav-faq/blob/master/faq/faq-safebrowsing.md

**Comment by mko-x** [comment] 2021-03-18 20:18
Seems to be related to that DDoS protection. It is not active for the other dbs like 

https://database.clamav.net/daily.cvd

**Comment by mko-x** [comment] 2021-03-18 20:25
See here:

https://community.cloudflare.com/t/clamav-freshclam-cannot-download-any-file-using-cloudflare-inc-ecc-ca-3-certificate-due-to-a-cookie-alert/252406

**Comment by mko-x** [comment] 2021-03-18 20:26
See also:

https://community.cloudflare.com/t/clamav-freshclam-cannot-download-any-file-using-cloudflare-inc-ecc-ca-3-certificate-due-to-a-cookie-alert/252406

**Comment by mko-x** [comment] 2021-03-18 20:31
There is nothing within the alpine configuration in this image which may explain the error after downloading 3 dbs from the same domain with success.

**Comment by DavidJFowler** [comment] 2021-03-22 10:38
> There is nothing within the alpine configuration in this image which may explain the error after downloading 3 dbs from the same domain with success.

Is this because the freshclam.conf files for the alpine images contain setting `SafeBrowsing yes`?
I started getting 403 and 429 errors in the last few days. Setting `SafeBrowsing no` has fixed this. Note also that clamav.net are currently implementing emergency measures to restrict requests: https://lists.clamav.net/pipermail/clamav-users/2021-March/010578.html

**Comment by uphlewis** [comment] 2021-03-22 11:34
+1 looks like cloudflare DDoS protection getting in the way. To confirm i'm trying to run a fresh container using the alpine image like so:

`docker run -d --name av mkodockx/docker-clamav:alpine`

And getting logs like so prior to the container existing/stopping itself:

```
[bootstrap] Initial clam DB download.
Mon Mar 22 10:40:35 2021 -> ClamAV update process started at Mon Mar 22 10:40:35 2021
Mon Mar 22 10:40:35 2021 -> daily database available for download (remote version: 26116)
Mon Mar 22 10:40:51 2021 -> Testing database: '/var/lib/clamav/tmp.c8f43/clamav-ee40adff6df2389fdf3affd90a56bc3a.tmp-daily.cvd' ...
Mon Mar 22 10:41:04 2021 -> Database test passed.
Mon Mar 22 10:41:04 2021 -> daily.cvd updated (version: 26116, sigs: 3964606, f-level: 63, builder: raynman)
Mon Mar 22 10:41:04 2021 -> main database available for download (remote version: 59)
Mon Mar 22 10:41:20 2021 -> Testing database: '/var/lib/clamav/tmp.c8f43/clamav-10262b4e28b7437596ddaab84b94ec68.tmp-main.cvd' ...
Mon Mar 22 10:41:27 2021 -> Database test passed.
Mon Mar 22 10:41:27 2021 -> main.cvd updated (version: 59, sigs: 4564902, f-level: 60, builder: sigmgr)
Mon Mar 22 10:41:27 2021 -> bytecode database available for download (remote version: 333)
Mon Mar 22 10:41:27 2021 -> Testing database: '/var/lib/clamav/tmp.c8f43/clamav-a60ff16ca3b3ab7b02e4e7aa6c22e5ac.tmp-bytecode.cvd' ...
Mon Mar 22 10:41:27 2021 -> Database test passed.
Mon Mar 22 10:41:27 2021 -> bytecode.cvd updated (version: 333, sigs: 92, f-level: 63, builder: awillia2)
Mon Mar 22 10:41:27 2021 -> safebrowsing database available for download (remote version: 49191)
Mon Mar 22 10:41:27 2021 -> ^downloadFile: Unexpected response (403) from https://database.clamav.net/safebrowsing.cvd
Mon Mar 22 10:41:27 2021 -> ^getcvd: Can't download safebrowsing.cvd from https://database.clamav.net/safebrowsing.cvd
Mon Mar 22 10:41:27 2021 -> Trying again in 5 secs...
Mon Mar 22 10:41:32 2021 -> safebrowsing database available for download (remote version: 49191)
Mon Mar 22 10:41:32 2021 -> ^downloadFile: Unexpected response (403) from https://database.clamav.net/safebrowsing.cvd
Mon Mar 22 10:41:32 2021 -> ^getcvd: Can't download safebrowsing.cvd from https://database.clamav.net/safebrowsing.cvd
Mon Mar 22 10:41:32 2021 -> Trying again in 5 secs...
Mon Mar 22 10:41:37 2021 -> safebrowsing database available for download (remote version: 49191)
Mon Mar 22 10:41:37 2021 -> !downloadFile: Unexpected response (403) from https://database.clamav.net/safebrowsing.cvd
Mon Mar 22 10:41:37 2021 -> !getcvd: Can't download safebrowsing.cvd from https://database.clamav.net/safebrowsing.cvd
Mon Mar 22 10:41:37 2021 -> Giving up on https://database.clamav.net...
Mon Mar 22 10:41:37 2021 -> !Update failed for database: safebrowsing
Mon Mar 22 10:41:37 2021 -> ^fc_update_databases: fc_update_database failed: HTTP GET failed (11)
Mon Mar 22 10:41:37 2021 -> !Database update process failed: HTTP GET failed (11)
Mon Mar 22 10:41:37 2021 -> !Update failed.
```

Attempting with SafeBrowsing disabled as @DavidJFowler suggested appears to mitigate the error. For anyone unfamiliar with clamav and/or this docker image, here's how:

1. Download the 'default' freshclam.conf from here to your host machine: https://github.com/mko-x/docker-clamav/blob/master/alpine/main/conf/freshclam.conf - in my example my local path to this file is `/Users/uphlewis/code/docker-clamav/freshclam.conf`
2. In the downloaded file, update `SafeBrowsing yes` to `SafeBrowsing no`
3. Run the container, mounting your custom freshclam.conf and set the environment variable `FRESHCLAM_CONF_FILE` which tells the container your custom config file path: `docker run -d --name av --mount type=bind,source=/Users/uphlewis/code/docker-clamav,destination=/mnt/clamav/ --env FRESHCLAM_CONF_FILE=/mnt/clamav/freshclam.conf mkodockx/docker-clamav:alpine`

**Comment by DavidJFowler** [comment] 2021-03-23 09:10
@mko-x  Do you think that `SafeBrowsing no` should be the default setting?

**Comment by uphlewis** [comment] 2021-03-23 11:01
So after attempting to deploy a clamav service to our staging cluster yesterday, i found that `SafeBrowsing no` is still not enough- actually there are 2 distinct problems. 

1. The CF DDoS protection (which disabling SafeBrowsing seems to circumvent)
2. The (aggressive) rate limiting (with a Retry-After of 6 hours 🤯)

I set the memory limit of the pod too low causing it to crash and repeatedly restart, which triggered the rate limiting at which point i was seeing 429 errors in the logs, despite having `SafeBrowsing off`.

**Comment by mko-x** [comment] 2021-03-25 22:48
We should think about changing that in the config we deliver by default. As long as it is necessary. Didn't see a PR yet, hasn't anyone fixed it? 🍡 

> @mko-x Do you think that `SafeBrowsing no` should be the default setting?

**Comment by uphlewis** [comment] 2021-03-25 23:01
Here's one @mko-x https://github.com/mko-x/docker-clamav/pull/108

**Comment by mko-x** [comment] 2021-03-26 22:44
Fixed by #108 for the moment to not break running services any more.

**Comment by eht16** [comment] 2021-03-29 20:06
To me it seems, starting with (even outdated) databases included in the Docker image reduces the problem of rate limiting.
Tested with the "buster-slim" image while being rate-limited, it successfully loaded patch updates for the outdated embedded database.
Running the Alpine image *without* embedded databases, `freshclam` instantly failed with 429 on that same rate-limited host.

@mko-x is there any reason why the Debian and Alpine images differ so much? Also the configuration files could be harmonized maybe.

I think it would be feasible to add a new flavor for the Alpine images with embedded databases (like it is in the Debian based images). Even with outdated databases, I think the image would offer a huge benefit: clamav in the image can start and use at least the available outdated signatures. On a rate-limited system the image without embedded databases, clamav would just fail to start (and either be auto-restarted by the controller or just staying dead).

**Comment by uphlewis** [comment] 2021-03-29 20:21
As long as you're not experiencing any startup errors, I don't believe you'll set off the rate limits in normal operation. I expect your db download/check/update requests when spinning up the buster-slim container would have contributed to you getting 429s when you then span up the alpine image if they were on the same host @eht16 ?

**Comment by eht16** [comment] 2021-03-29 20:27
In my tests, I triggered the rate limiting on purpose, actually.
But I experienced the rate-limiting a few days in a Kubernetes cluster with two `mkodockx/docker-clamav` Pods (in different namespaces) and on restarting one of the Pods, the rate-limiting kicked in.

There might be various reasons for the rate-limiting kicking in, I guess. The idea is to stuff the Docker images with the databases at build time so the containers have something to work with at runtime in case of any networking errors (like rate-limiting).

**Comment by mko-x** [comment] 2021-03-29 23:40
Anyway, we may think about offering something like embedded database images. It might be useful in some use cases - for closed networks or embedded scenarios maybe. That will probably lead to other problems not about rate limiting but bandwidth or traffic limiting as the size grows with the dbs.

@eht16 Did you already built an image with embedded dbs? Would you mind creating a PR?

**Comment by uphlewis** [comment] 2021-03-29 23:57
Presumably this PR might need to parse DatabaseDirectory from any custom clamd/freshclam confs and move the seed databases to that custom directory IF the db files don't currently exist- or would it be cleaner/better to add an explicit environment variable for database directory? Wouldn't want a stale seed db to overwrite a db specifically mounted from a PV.

**Comment by mko-x** [comment] 2021-03-30 00:09
I don't see the use case for using DatabaseDirectory within the av container. As any custom contet could be virtually mounted anywhere, why should you need a special db dir path in the container?

**Comment by mko-x** [comment] 2021-04-01 20:09
I created a new image version:

alpine-idb-amd64

This is bundled with the database files.

See more at https://github.com/mko-x/docker-clamav/blob/master/alpine/main-idb/README.md

**Comment by mko-x** [comment] 2021-04-01 20:14
If you experience database download errors - use alpine-idb-amd64 instead.

**Closed by mko-x** 2021-04-01 20:14 UTC

**Comment by mko-x** [comment] 2021-04-01 20:16
See https://www.mail-archive.com/clamav-users@lists.clamav.net/msg49810.html

**Comment by eht16** [comment] 2021-04-06 20:40
Thanks a lot for "alpine-idb-amd64". Much appreciated.

**Comment by mko-x** [comment] 2021-04-06 20:48
You're welcome. Appreciate your impulse. I think it is a good idea for several use cases.

**Comment by iJebus** [comment] 2021-04-07 04:26
I'm still getting hit with 429's while using alpine-idb-amd64; I'm guessing building manually with the very latest might get around this.

**Comment by igilabert** [comment] 2021-04-07 07:32
For me, the new "alpine-idb-amd64" image it's working. Would it update the database automatically?

**Comment by mko-x** [comment] 2021-04-10 14:59
> I'm still getting hit with 429's while using alpine-idb-amd64; I'm guessing building manually with the very latest might get around this.

Well, as Joel Esler wrote: It depends on how often your machine i.e. your IP tries to download the dbs. With the alpine-idb-amd64 just guarantees that you have somehow a signature database - even if there is no download possible.

**Comment by mko-x** [comment] 2021-04-10 15:01
> For me, the new "alpine-idb-amd64" image it's working. Will it update the database automatically?

Yes - freshclam is started just like in the regular images. The only difference is that you already have initial databases included. Updates will be downloaded if possible.

**Comment by iJebus** [comment] 2021-04-13 07:51
> > I'm still getting hit with 429's while using alpine-idb-amd64; I'm guessing building manually with the very latest might get around this.
> 
> Well, as Joel Esler wrote: It depends on how often your machine i.e. your IP tries to download the dbs. With the alpine-idb-amd64 just guarantees that you have somehow a signature database - even if there is no download possible.

I guess the potential issue is that you won't be able to start even if you have built with the latest db because it errors out when checking and hitting the limit. Maybe it would be nice to have an environment variable to enable/disable freshclam but at the same time... I don't know. It's probably not worth the effort. I'm on the new image now and everything has been fine so thanks to those involved for putting it together.

**Comment by uphlewis** [comment] 2021-04-13 09:43
I would have loved an env var to disable freshclam last weekend. I was working in the car and didn't have any Internet; couldn't get the container running at all despite having dbs mounted

**Comment by shaunakv1** [comment] 2021-04-16 17:13
mkodockx/docker-clamav:alpine-idb-amd64 image works for us ( at-least so far) it even boots real fast!  Just to be sure though this will still attempt to update the db at regular intervals right?

**Comment by mko-x** [comment] 2021-04-17 19:48
You could make use of:
```bash
OnErrorExecute STRING
```

And execute something like `kill freshclam`

See https://linux.die.net/man/5/freshclam.conf

**Comment by farces** [comment] 2021-04-19 02:29
This is caused by this change made by the clamav team: https://blog.clamav.net/2021/04/are-you-still-attempting-to-download.html

`Safebrowsing no` should absolutely be the default on all versions below 0.103.2 or you will get stuck in a loop that starts with a 403 Forbidden and ends with a restart-loop caused by hitting the rate limit (429 Too Many Requests).
